name: tf-metal
channels:
  - apple
  - conda-forge
dependencies:
  - python=3.10.0  
  - pip==22.3.1
  - tensorflow-deps
  - ipykernel==6.19.2 # Comment if not using jupyter
  - matplotlib==3.6.2
  - opencv-python==4.6.0.66
  - flask==2.2.2
  - werkzeug==2.2.2
  - numpy==1.23.2

  # PyPI packages
  - pip:
    - tensorflow-macos==2.9
    - tensorflow-metal==0.5  
    
  # For Silicon ARM-based Macs only -> subject to change -> 2.9 for macos and 0.5 for metal works perfectly as of December '22